'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.DTSReports.DataSources.ADO
    
    Partial Public Class Settings
        
        '''<summary>
        '''ProviderName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProviderName As Global.DotNetNuke.UI.UserControls.LabelControl
        
        '''<summary>
        '''ProviderNameDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProviderNameDropDown As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ConnStrLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConnStrLabel As Global.DotNetNuke.UI.UserControls.LabelControl
        
        '''<summary>
        '''ConnStrTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConnStrTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ParamPrefixLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ParamPrefixLabel As Global.DotNetNuke.UI.UserControls.LabelControl
        
        '''<summary>
        '''ParamPrefixTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ParamPrefixTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''SqlDataSourceCommonSettingsControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceCommonSettingsControl As Global.DotNetNuke.Modules.DTSReports.Controls.SqlDataSourceCommonSettingsControl
    End Class
End Namespace
